<div class="area">
	<div class="help"> 
		<p>帮助</p>
	</div>
	
	<?=$this->showErrors()?>
	
	<div class="nr">
		<h2>编辑图集</h2>

		<form action="" method="post">
			<table width="100%" cellspacing="1" class="form">
			<tbody>
			    <tr>
				    <td width="80">标    题</td>
				    <td><input type="text" name="title" value="<?=$this->param('title', $this->album['title']) ?>" size="45" class="input"/></td>
			    </tr>
			    <tr>
				    <td>短标题</td>
				    <td><input type="text" name="stitle" value="<?=$this->param('stitle', $this->album['stitle']) ?>"  class="input" /></td>
			    </tr>
			    <tr class="alt">
				    <td>分    类</td>
				    <td><?=$this->formSelect('cid', $this->param('cid', $this->album['cid']), '', $this->categories)?></td>
			    </tr>
			    <tr>
    				<td>模　　板</td>
	    			<td><?=$this->formSelect('template', $this->param('template', $this->album['template']), null, $this->templates)?></td>
			    </tr>
			    <tr>
		    		<td>链接</td>
			    	<td><input type="text" name="link" value="<?=$this->param('link', $this->album['link']) ?>" class="input" size="45"/></td>
			    </tr>
			    <tr>
				    <td>来源</td>
				    <td><input type="text" name="source" value="<?=$this->param('source', $this->album['source']) ?>" class="input"/></td>
			    </tr>
			    <tr>
    				<td>作者</td>
	    			<td><input type="text" name="author" value="<?=$this->param('author') ?>"  class="input"/></td>
			    </tr>
			    <tr>
		    		<td>关 键 字</td>
			    	<td><input type="text" name="keywords" value="<?=$this->param('keywords', $this->album['keywords']) ?>"  class="input"  size="45"/></td>
			    </tr>
			    <tr>
				    <td>简　　介</td>
    				<td><textarea id="intro" name="intro" cols="" rows="" class="abs"><?=$this->param('intro', $this->album['intro']) ?></textarea></td>
			    </tr>
			    <tr>
	    			<td>&nbsp;</td>
		    		<td><button type="submit" name="submit">修改图集</button></td>
			    </tr>
			</tbody>
			</table>
		</form>
	</div>
</div>