<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>CMS_文章列表</title>
<?=$this->headLink() ?>
<?=$this->headScript() ?>
<script>
function on_submit(obj)
{
	if(obj.title.value!='')obj.action="/contents/article/index/order/postdate";
	if(obj.author.value!='')obj.action="/contents/article/index/order/postdate";
	if(obj.realname.value!='')obj.action="/contents/article/index/order/postdate";
	if(obj.article_type.checked)obj.action="/contents/article/index/order/postdate";
}
</script>
</head>

<body>
<div class="area">
	<div class="help">
    <p>帮助</p>
    <p>1、此处为新华社文章列表;</p>    
    <p class="soart">
    	<!--form action="/contents/article" name="search_form" method="post" onsubmit="on_submit(this)">
        	<label>标题搜索:<input class="input" type="text" name="title" value="<?=$this->title?>" size="16" /></label>
            <label>作者搜索:<input class="input" type="text" name="author" value="<?=$this->author?>" size="8" /></label>
            <input type="submit" value="显示"></button>
        </form-->
    </p>    
    </div>
	<div class="nr">
    	<h2>
        	<!--a href="#nogo">篮球</a>&gt;<a href="#nogo">NBA</a-->
        </h2>
    	<table cellpadding="0" cellspacing="0" border="0" width="100%" class="list">
        	<tr>
            	<th>aid</th>
                <th>标题</th>
                <th>作者</th>
                <th>发布时间</th>
                <th>已添加频道</th>
                <th>操作</th>
            </tr>
    <?php foreach ($this->result as $key => $value): ?>
            <tr>
        	<td><?=$value['aid']?></td>
                <td><a href="/contents/xinhua/preview/aid/<?=$value['aid'] ?>" target="_self"><?=$this->escape($value['title']) ?></a></td>
                <td><?=$this->escape($value['author']) ?></td>
                <td><?=$this->escape(date("Y-m-d H:i:s",$value['postdate'])) ?></td>
                <td><?=$value['inchannel'] ?>&nbsp;</td>
                <td><a href="/contents/xinhua/push/aid/<?=$value['aid'] ?>">添加至本频道</a></td>
            </tr>
    <?php endforeach;  ?>
        </table>
        
        
    </div>
    
    <div class="fy">
		<?=$this->pagebar ?>
	</div>
    </div>
    


</body>
</html>
