<div class="area">
<div class="help"> 
	<p>帮助</p>
	<p>1、此处为(<?=$this->vote['title']?>)所属的投票题目管理;</p>      
	<p>2、投票题目是显示在投票界面里的问题，支持单题目，也支持多个题目;</p> 
	<p>3、状态有正常和删除两种,正常状态，正常显示；删除状态，不显示在界面或接口里;</p> 
</div>
<div class="nr">
<h2>
<button onclick="window.location.href='/vote/problem/index/vid/<?=$this->vid?>'">返回</button>
<a href="#nogo">修改投票题目标题</a>        	
</h2>
	<form action="/vote/problem/update" method="post">
	<table cellpadding="0" cellspacing="0" border="0" width="100%" class="list">
	<tbody>
			<tr>
			<td>名称</td>
			<td><input type="text" name="title" value="<?=$this->data['title']?>" size="40"/>建议在20个汉字以内</td>
		</tr>
		<tr>
			<td>排序</td>
			<td><input type="text" name="orderby" value="<?=$this->data['orderby']?>" /></td>
		</tr>
		<tr>
			<td>状态</td>
			<td><select name="status" >				
					<option value="0" label="正常" <?=$this->select[0]?>>正常</option>				
					<option value="1" label="删除" <?=$this->select[1]?>>删除</option>				
				</select></td>
		</tr>	
		<tr>
			<td></td>
			<td align="left"><input type="hidden" name="vid" value="<?=$this->data['vid']?>" />
			<input type="hidden" name="pid" value="<?=$this->data['pid']?>" />
			<input type="submit" value="   提 交   " /></td>
		</tr>
	</tbody>
	</table>
	</form>
	</div>
</div>

