
<div class="area">
	<div class="help"> 
		<p>帮助</p>
		<p>1. 只允许上传jpg、png和gif文件</p>
		<p>2. 注意控制文件大小</p>
	</div>

	<div class="nr">
	<h2>
		<button onclick="window.location.href='/albums/photos?aid=<?=$this->album['aid']?>'">返回图集</button>
		当前图集: <strong><?=$this->album['title']?></strong>
	</h2>
	<link href="/scripts/uploadify/uploadify.css" media="screen" rel="stylesheet" type="text/css" >
	<script type="text/javascript" src="/scripts/uploadify/swfobject.js"></script>
	<script type="text/javascript" src="/scripts/uploadify/jquery.uploadify.v2.1.4.js"></script>
	<script type="text/javascript">
	$(function() {
	      $('#file_upload').uploadify({
		  'uploader'    : '/scripts/uploadify/uploadify.swf',
		  'script'      : '/albums/photos/doupload/aid/<?=$this->album['aid']?>/',
		  'cancelImg'   : '/scripts/uploadify/cancel.png',
		  'fileExt'     : '*.jpg;*.jpeg;*.png',
		  'fileDesc'	: 'JPG图片;PNG图片',
		  'fileDataName': 'photos[]',
		  'removeCompleted' : false,
		  'multi'       : true,
		  'scriptData'  : {'PHPSESSID': '<?=session_id()?>'},
		  'onAllComplete' : function () {
			alert('上传成功');		
         //   window.location = '/albums/photos/?aid=<?=$this->album['aid']?>';
		  }

		}); 
	});
      </script> 
	<div id="demo" style="padding: 10px"> 
		<input type="file" id="file_upload" name="file_upload" />
		<br />
		<input type="button" onclick="$('#file_upload').uploadifyUpload();" value="开始上传" style="padding: 4px 10px"/>
	</div>

	</div>

</div>
