<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>CMS_文章列表</title>
<?=$this->headLink() ?>
<?=$this->headScript() ?>
<script>
function recommend(aid,level)
{
	if(level == 9)
	{
		var msg='确定取消推荐此文章吗?';
	}else
	{
		var msg='确定推荐此文章吗?';
	}
	if(confirm(msg))
	{
		window.location="/contents/article/recommend/id/"+aid+"/level/"+level;
	}
}
function add()
{
	window.location='/contents/article/add/cid/'+$('#cid').val();
}
function on_submit(obj)
{
	if(obj.title.value!='')obj.action="/contents/article/index/order/postdate";
	if(obj.author.value!='')obj.action="/contents/article/index/order/postdate";
	if(obj.realname.value!='')obj.action="/contents/article/index/order/postdate";
	if(obj.article_type.checked)obj.action="/contents/article/index/order/postdate";
}

if(navigator.userAgent.indexOf("Firefox")<=0){  
      //alert('警告：在非Firefox浏览器中添加或编辑视频内容，可能会造成embed标签缺失，请使用Firefox系列浏览器');
}  
</script>
</head>

<body>
<div class="area">
	<div class="help">
    <p>帮助</p>
    <p>1、此处为文章列表;</p>    
    <p>2、选择隐藏在发布文章时则不显示此分类.</p>
    <p class="soart">
    	<form action="/contents/article" name="search_form" method="post" onsubmit="on_submit(this)">
            <label>分类搜索:<?=$this->formSelect('cid', $this->cid, null, $this->category_options)?></label>
        	<label>标题搜索:<input class="input" type="text" name="title" value="<?=$this->title?>" size="16" /></label>
            <label>作者搜索:<input class="input" type="text" name="author" value="<?=$this->author?>" size="8" /></label>
            <label>发布者搜索:<input class="input" type="text" name="realname" value="<?=$this->realname?>" size="8" /></label>
			<label>新闻来源:
					<?php echo $this->formSelect('publisher_id', $this->publisher_id, array('onchange'=>'this.form.publisher.value=this.options[this.selectedIndex].innerText'), $this->publisher_select) ?></label>
            <br/>
            <label><input type="checkbox" name="article_type" value="1" <?=$this->article_type?'checked':''?> />是否约稿</label>
            <label><input type="checkbox" name="article_nopic" value="1" <?=$this->article_nopic?'checked':''?> />无图内容</label>

<span>
<select id="year" name="year">
    
</select>年
</span>

<span id="select_month" style="display: inline;">
<select id="month" name="month">
    
</select>月
</span>
<span id="select_day" style="display: inline;"><select id="day" name="day">
    
</select>日</span>
<span id="join" style="display: inline;">至</span>
<span>
<select id="end_year" name="end_year">
    
</select>年
</span>

<span id="select_month" style="display: inline;">
<select id="end_month" name="end_month">
    
</select>月
</span>
<span id="select_day" style="display: inline;">
<select id="end_day" name="end_day">
    
</select>日</span>

<script>
d=new Date();
startD= new Date(d.getTime()-60*60*24*369*2*1000);

dbYear="<?=$this->year?>";
dbMonth="<?=$this->month?>";
dbDay="<?=$this->day?>";
end_dbYear="<?=$this->end_year?>";
end_dbMonth="<?=$this->end_month?>";
end_dbDay="<?=$this->end_day?>";

year=dbYear!='' ? dbYear : startD.getFullYear();
month=dbMonth!='' ? dbMonth : startD.getMonth()+1;
day=dbDay!='' ? dbDay : startD.getDate();
end_year=end_dbYear!='' ? end_dbYear : d.getFullYear();
end_month=end_dbMonth!='' ? end_dbMonth : d.getMonth()+1;
end_day=end_dbDay!='' ? end_dbDay : d.getDate();
                          
for(i=d.getFullYear();i>=2001;i--){
    selected=i==year ? 'selected' : '';
    end_selected=i==end_year ? 'selected' : '';
    $("#year").append('<option label="'+i+'" value="'+i+'" '+selected+'>'+i+'</option>');
    $("#end_year").append('<option label="'+i+'" value="'+i+'" '+end_selected+'>'+i+'</option>');    
}

for(i=1;i<=12;i++){
    iStr=i>9 ? i : '0'+i;
    selected=i==month ? 'selected' : '';
    end_selected=i==end_month ? 'selected' : '';
    $("#month").append('<option label="'+iStr+'" value="'+iStr+'" '+selected+'>'+iStr+'</option>'); 
    $("#end_month").append('<option label="'+iStr+'" value="'+iStr+'" '+end_selected+'>'+iStr+'</option>');   
}

for(i=1;i<=31;i++){
    iStr=i>9 ? i : '0'+i;
    selected=i==day ? 'selected' : '';
    end_selected=i==end_day ? 'selected' : '';
    $("#day").append('<option label="'+iStr+'" value="'+iStr+'" '+selected+'>'+iStr+'</option>'); 
    $("#end_day").append('<option label="'+iStr+'" value="'+iStr+'" '+end_selected+'>'+iStr+'</option>');      
}

</script>
            
            <input type="submit" value="显示"></button>
        </form>
    </p>    
    </div>
	<div class="nr">
    	<h2>
            <button onclick="location.href='/contents/article/pushcid'">推送分类</button>
        	<button onclick="add()">添加文章</button>
        	<!--a href="#nogo">篮球</a>&gt;<a href="#nogo">NBA</a-->
        </h2>
    	<table cellpadding="0" cellspacing="0" border="0" width="100%" class="list">
        	<tr>
            	<th>aid</th>
                <th>标题</th>
                <th>分类</th>
                <th>权重</th>
                <th>发布者</th>
                <th title="按权重和发布时间排序">
                	<?php if($this->order=='recommend'){?>是否推荐<img src="/images/order_down.gif"/>
                	<?php }else{?><a href="/contents/article/index?order=recommend&<?=$this->search_para?>">是否推荐</a><?php }?>
                </th>
                <!--th title="按点击次数和发布时间排序">
                	<?php if($this->order=='pv'){?>点击次数<img src="/images/order_down.gif"/>
                	<?php }else{?><a href="/contents/article/index?order=pv&<?=$this->search_para?>">点击次数</a><?php }?>
                </th-->
                <th title="按发布时间排序">
                	<?php if($this->order=='postdate'){?>发布时间<img src="/images/order_down.gif"/>
                	<?php }else{?><a href="/contents/article/index?order=postdate&<?=$this->search_para?>">发布时间</a><?php }?>
                </th>
                <th>评论</th>
                <th>操作</th>
            </tr>
    <?php foreach ($this->result as $key => $value): 
		$value['href']= ($value['islink'] ? 'h' : $this->push_url).substr($value['url'],1);
	?>
            <tr>
        	<td><?=$value['aid']?></td>
                <td style="width:45%;"><a href="<?=$value['href']?>" target="_blank"><?=$this->escape($value['title']) ?></a></td>
                <td><a href="/contents/article/index/cid/<?=$value['cid']?>"><?=$this->escape($value['category']) ?></a></td>
                <td><?=$value['level']?></td>
                <td><?=$this->escape($value['realname']) ?></td>
                <td><a href="#here"  onclick="recommend(<?=$value['aid'] ?>,<?=$value['level']?>)"><img src="<?=$value['level']==9 ? '/images/star_ok.gif' : '/images/star_no.gif' ?>" /></a></td>
                <!--td><?=$value['pv']?></td-->
                <td><?=$this->escape(date("Y-m-d H:i:s",$value['postdate'])) ?></td>
                <td>
                <iframe scrolling="no" style="border:0 none;height:27px;width:50px" src="http://discuss.v1.cn/discuss/comments/optcheckComment.jhtml?newsId=<?=$value['aid'];?>&newsType=<?=$this->channel?>&style=font-size:13px;color:000000"></iframe>
                </td>
                <td>
                <a href="<?=$value['href']?>" target="_blank"><img src="/theme/default/image/preview.png" alt="预览" title="预览" /></a>
                <a href="javascript:void(0);" onclick="window.open('/contents/article/edit/id/<?=$value['aid'] ?>','编辑','resizable=yes,width=1000px,scrollbars=yes');"><img src="/theme/default/image/edit.png" alt="编辑" title="编辑" /></a>
                <a href="#nogo" onclick="window.location='/contents/article/publish/id/<?=$value['aid'] ?>'"><img src="/theme/default/image/publish.png" alt="发布" title="发布" /></a>
                <a href="#nogo" onclick="if(confirm('确定删除吗?'))window.location='/contents/article/delete/id/<?=$value['aid'] ?>'"><img src="/theme/default/image/delete.png" alt="删除" title="删除" /></a>
                <a href="/contents/article/share/id/<?=$value['aid'] ?>"><img src="/theme/default/image/share.png" alt="分享到频道" title="分享到频道" /></a>         
                </td>
            </tr>
    <?php endforeach;  ?>
        </table>
        
        
    </div>
    
    <div class="fy">
		<?=$this->pagebar ?>
	</div>
    </div>    
</body>
</html>