

<div class="area">
    <div class="help"> 
		<p>帮助</p>
        <p>1、搜索支持*标</p>
        <p>2、TM栏目是合作单位天脉视频的栏目名称　</p>
        <p>
            <form method="get" name="search_form" action="">
                关键字搜索:
                <label>
                    <select name="searchType">
                        <option value="title" <?if($_GET['searchType']=='title'){?>selected<?}?>>按标题</option>
                        <option value="filename" <?if($_GET['searchType']=='filename'){?>selected<?}?>>按文件名</option>
                        <option value="columnName" <?if($_GET['searchType']=='columnName'){?>selected<?}?>>按栏目名</option>
                    </select>
                </label>
                <label>
                <?=$this->formSelect('cid', $this->param('cid'), '', $this->categories)?>
                </label>
                <label>
                <input type="text" size="16" value="<?=$_GET['searchKey']?>" name="searchKey" class="input"></label>
                <input type="hidden" value="<?=$this->set['sid']?>" name="sid"><input type="submit" value="显示">
            </form>
        </p>
	</div>

	<div class="nr">
	<h2>
		视频分类列表 
	</h2>
    
    <?php if (!$this->video): ?>
    <p style="padding: 10px">暂未无视频</p>
    <?php else: ?>
    <form action="" method="post">
	<table width="100%" cellpadding="4" cellspacing="1">
	       <tr>
            	<th>&nbsp;&nbsp;删</th>
                <th>&nbsp;&nbsp;vid</th>
                <th>&nbsp;&nbsp;原文件名</th>
                <th>&nbsp;&nbsp;分类</th>
                <th>&nbsp;&nbsp;TM栏目</th>
                <th>&nbsp;&nbsp;标题</th>
                <th>&nbsp;&nbsp;来源</th>
                <th>&nbsp;&nbsp;关键字</th>
                <th>&nbsp;&nbsp;状态</th>	
                <th>&nbsp;&nbsp;上传时间</th>
            </tr>
    <?php $i = 0; foreach ($this->video as $p): ?>
    <tr>
         <td width="10px"><input type="checkbox" name="delete[<?=$p['vid']?>]" value="1" /></td>
         <td width="1px"><?=$p['vid']?></td>
         <td><div style="overflow: hidden; float: left; width: 140px;"><?=$p['videoLink']?></div></td>
         <td><?=$p['categoryName']?></td>
         <td><?=$p['columnName']?></td>
         <td width="200px"><input type="text" value="<?=$p['title']?>" style="width: 200px" size="50" name="title[<?=$p['vid']?>]"></td>
         <td width="110px"><input type="text" value="<?=$p['source']?>" style="width: 110px" size="50" name="source[<?=$p['vid']?>]"></td>
         <td width="110px"><input type="text" value="<?=$p['keyword']?>" style="width: 110px" size="50" name="keyword[<?=$p['vid']?>]"></td>
         <td width="50px"><?=$p['isTranscoding']?></td>
         <td width="160px"><?=$this->escape($p['uploadtime'])?></td>
	</tr>
    <?php endforeach; ?>
	</table>
    <input type="hidden" name="searchType" value="<?=$_GET['searchType']?>" />
    <input type="hidden" name="searchKey" value="<?=$_GET['searchKey']?>" />
    <input type="hidden" name="sid" value="<?=$this->set['sid']?>" />
    <input type="submit" value=" 修 改 " /><?=$this->pagebar?>
    </form>
    <?php endif; ?>
	</div>
</div>