
    <div class="video_play" id="playDiv">
        <object width="630" height="534" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,115,0" classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="play1">
            <param name="movie" value="http://www.v1.cn/player/cloud/cloud_player.swf" />
            <param name="bgcolor" value="#000000" />
            <param name="FlashVars" value="id=601039&amp;startSwfUrl=http://www.v1.cn/player/cloud/loading.swf&amp;videoUrl=<?=$this->videoUrl?>" />
            <param name="allowScriptAccess" value="always" />
            <param name="allowFullScreen" value="true" />
            <param name="wmode" value="opaque" />
            <embed width="630" height="534" src="http://www.v1.cn/player/cloud/cloud_player.swf" flashvars="id=601039&amp;startSwfUrl=http://www.v1.cn/player/cloud/loading.swf&amp;videoUrl=<?=$this->videoUrl?>" name="play1" bgcolor="#000000" allowscriptaccess="always" allowfullscreen="true" wmode="opaque" cover="" type="application/x-shockwave-flash"></embed>
        </object>
    </div>
