

<div class="area">
    <div class="help"> 
		<p>帮助</p>
        <p>1、视频文件来自于FTP上传的目录<?=$this->uploadDir?></p>
        <p>2、视频文件将放置于此目录进行转码<?=$this->transcodeDir?></p>
        <p>3、此配置在用户“编辑用户”中进行配置</p>
	</div>

	<div class="nr">
	<h2>
		未处理视频列表
	</h2>    
    <?php if (!$this->fileList): ?>
    <p style="padding: 10px">没有是可处理视频</p>
    <?php else: ?>
    <form action="" method="post" onsubmit="return saveSubmit();">
    <table width="100%" cellpadding="4" cellspacing="1">
    <tr>
        <th>第一步：选择分类</th>
    </tr>
    <tr>
        <td><?=$this->formSelect('cid', $this->param('cid'), '', $this->categories)?></td>
	</tr>
	</table>
	<table width="100%" cellpadding="4" cellspacing="1">
            <tr>
            	<th colspan="5">第二步：选择文件并填写标题</th>
            </tr>
           <tr>
            	<th>&nbsp;</th>
                <th>&nbsp;&nbsp;文件名</th>
                <th>&nbsp;&nbsp;扩展名</th>
                <th>&nbsp;&nbsp;路径</th>
                <th>&nbsp;&nbsp;标题</th>
                <th>&nbsp;&nbsp;来源</th>
                <th>&nbsp;&nbsp;关键字</th>
            </tr>
    <?
        foreach ($this->fileList as $key=>$p): 
        $file=pathinfo($p);
    ?>
    <tr>
         <td width="10px"><input type="checkbox" name="files[<?=$key?>]" value="<?=$p?>" /></td>
         <td><?=$file['filename']?></td>
         <td><?=$file['extension']?></td>
         <td><?=$p?></td>
         <td width="200px"><input type="text" value="<?=$file['filename']?>" style="width: 200px" size="50" name="title[<?=$key?>]"></td>
         <td width="110px"><input type="text" value="<?=$this->realname?>" style="width: 110px" size="50" name="source[<?=$key?>]"></td>
         <td width="110px"><input type="text" value="<?=$file['filename']?>" style="width: 110px" size="50" name="keyword[<?=$key?>]"></td>
	</tr>
    <?php endforeach; ?>
	</table>
    <input id="saveButton" type="submit" value=" 保 存 " />
    </form>
    <?php endif; ?>
	</div>
</div>
<script>
    function saveSubmit(){
        var cid=$("#cid").val();
        if(cid==0){
            alert('请选择分类');
            return false;
        }
        return true;
    }
</script>