
<div class="area">
	<div class="help"> 
		<p>帮助</p>
		<p>1. 只允许上传flv、mp4和3gp文件</p>
		<p>2. 注意控制文件大小</p>
        <p>3. 文件将上传至配置文件中video参数指定的left/right目录中,如需转码,请按照转码要求进行目录配置</p>
	</div>

	<div class="nr">
	<h2>
		<button onclick="javascript: history.go(-1)">返回视频列表</button>
		当前视频集:<strong><?=$this->set['title']?></strong>
	</h2>
	<link href="/scripts/uploadify/uploadify.css" media="screen" rel="stylesheet" type="text/css" >
	<script type="text/javascript" src="/scripts/uploadify/swfobject.js"></script>
	<script type="text/javascript" src="/scripts/uploadify/jquery.uploadify.v2.1.4.js"></script>
	<script type="text/javascript">
	$(function() {
          $('#file_upload').uploadify({
    		  'uploader'    : '/scripts/uploadify/uploadify.swf',
    		  'script'      : '/video/video/doupload/sid/<?=$this->set['sid']?>/',
    		  'cancelImg'   : '/scripts/uploadify/cancel.png',
    		  'fileExt'     : '*.avi;*.mpg;*.mpeg;*.mp4;*.flv;*.3gp;*.ts',
    		  'fileDesc'	: '*.avi;*.mpg;*.mpeg;*.mp4;*.flv;*.3gp;*.ts',
    		  'fileDataName': 'video[]',
    		  'removeCompleted' : false,
    		  'multi'       : false,
              'sizeLimit'   : 131072000,
    		  'scriptData'  : {'PHPSESSID': '<?=session_id()?>',"coverLogo":"right"},
               /*
              'onComplete' : function(event, ID, fileObj, response, data){
                console.log(fileObj);
                console.log(response);
              },
              */
              'onAllComplete' : function () {
    			alert('上传成功');		
                window.location = '/video/video/?sid=<?=$this->set['sid']?>';
    		  }
		  });
          $("input[name='coverLogo']").click(function(){
              coverLogo=$($("input:checked")).val();
              $('#file_upload').uploadifySettings('scriptData',{'PHPSESSID': '<?=session_id()?>',"coverLogo":coverLogo});
          });
	});
      </script> 
	<div id="demo" style="padding: 10px"> 
		<input type="radio" name="coverLogo" value="left">压左边<input checked type="radio" name="coverLogo" value="right">压右标<br /><br />
        <input type="file" id="file_upload" name="file_upload" /><br />
		<input type="button" onclick="$('#file_upload').uploadifyUpload();" value="开始上传" style="padding: 4px 10px"/>
	</div>

	</div>

</div>
