<?=$this->doctype('XHTML1_TRANSITIONAL')?>

<html>
  <head>
    <base target="_self">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?=$this->headTitle()?>
    <?=$this->headLink()?>
    <?=$this->headScript()?>
    <?=$this->headStyle()?>
  </head>
  <body>
    <div id="main" style="margin-left: 0px;">
        <?=$this->layout()->content?>
    </div>

  </body>
</html>