<?=$this->doctype('XHTML1_TRANSITIONAL')?>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?=$this->headTitle()?>
  </head>
  <frameset rows="110,*" cols="*" frameborder="no" border="0" framespacing="0">
  <frame src="/system/index/top" name="topFrame" scrolling="No" noresize="NORESIZE" id="topFrame" title="topFrame" />
  <frameset rows="*" cols="160,*" framespacing="0" frameborder="no" border="0">
    <frame src="/system/index/menu" name="leftFrame" noresize="noresize" id="leftFrame" title="leftFrame" />
    <frame src="http://work.g.v1game.cn/cut/updateGame.php" name="mainFrame" id="mainFrame" title="mainFrame" />
  </frameset>
</frameset>
<noframes><body>
</body>
</noframes>
</html>
