<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>CMS_添加活动预告</title>
<?php echo $this->headLink(); ?>
<script type="text/javascript" src="/scripts/jquery/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="/scripts/date/WdatePicker.js"></script>
<script type="text/javascript" src="/scripts/FckEdit.js"></script>
<style>
	
</style>
</head>
<body>
	<div class="area">
		<div class="nr">
			<h2>
				<a href="javascript:void(0);">添加预告</a>
			</h2>
			<div class="con">
				<form action="" method="post">
					<table width="100%" border="0" cellspacing="0" cellpadding="0" id="adact">
						<tr>
							<td width="70" align="center" valign="middle">活动标题</td>
							<td>
								<input type="text" class="input" size="30" id="title" name="title" value="" /> 
								<span id="title_length_view">文字最大字节数：45，<span id="title_length"></span></span>
							</td>
						</tr>
						<tr>
							<td width="70" align="center" valign="middle">活动描述</td>
							<td>
								<input type="text" class="input" size="60" id="desc" name="desc" value="" /> 
								<span id="desc_length_view">文字最大字节数：160，<span id="desc_length"></span></span>
							</td>
						</tr>
						<tr>
							<td width="70" align="center" valign="middle">奖品图片（PC）</td>
							<td>
								<input type="text" class="input" size="60" name="pc_img_url"/> 
								<a href="javascript:void(0);" class="upload">上传</a><br/>
								<div class="img_preview"></div>
							</td>
						</tr>
						<tr>
							<td width="70" align="center" valign="middle">奖品图片（Phone）</td>
							<td>
								<input type="text" class="input" size="60" name="phone_img_url"/> 
								<a href="javascript:void(0);" class="upload">上传</a><br/>
								<div class="img_preview"></div>
							</td>
						</tr>
						
						<tr>
							<td width="70" align="center" valign="middle">游戏ID</td>
							<td>
								<input type="text" class="input" id="game_id" name="game_id"/>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center" valign="middle">
								<input type="submit" name="submit" value="保存内容" />
							</td>
			  			</tr>
					</table>
				</form>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		var $title = $('#title'),
			$desc = $('#desc'),
			$upload = $('.upload');

		// 文字个数显示
		$title.keyup(function(){
			checkLenth(title,'title_length_view','title_length',45);
		});
		$desc.keyup(function(){
			checkLenth(desc,'desc_length_view','desc_length',160);
		});
		checkLenth($title.get(0),'title_length_view','title_length',45);
		checkLenth($desc.get(0),'desc_length_view','desc_length',160);

		// 图片上传
		$upload.click(function(){
			upload(this);
		});
		//TODO 表单提交验证


		/**
		 * 提示文本框数据长度
		 */
		function checkLenth(obj,view_id,length_id,max_length)
		{
			var strlength=count_length(obj.value);
			if(strlength <= max_length)
			{
				$('#'+view_id).removeClass().addClass('info');
				$('#'+length_id).text('还剩'+(max_length-strlength)+'字节');
			}else
			{
				$('#'+view_id).removeClass().addClass('info').addClass('war');
				$('#'+length_id).text('超出'+(strlength-max_length)+'字节');
			}
		}

		/**
		 * 检测文本框数据长度
		 */
		function count_length(objValue)
		{
			return objValue.replace(/[^\x00-\xff]/g,"**").length;
		}

		/**
		 * 上传窗口
		 */
		function upload(obj)
		{
			window.lastUploadForm = $(obj).prev();
			var dialog_url="/resource/index/index/type/0/name//cid/"+$("#cid").val();
			if (!window.showModalDialog) {
				alert('抱歉，暂不支持该浏览器，请切换至火狐浏览器使用，多谢！');
				return false;
			}
		    var imgurl = window.showModalDialog(dialog_url, "", "dialogHeight:265px; dialogWidth:400px; resizable:0; scroll:0; status:0; unadorned:0;");
		    if(imgurl == undefined) return false;
		    $(obj).prev().val(imgurl);
		    if(imgurl)$(obj).nextAll('.img_preview').html('<a href="'+ imgurl +'" target="_blank"><img style="height:100px;" src="'+ imgurl +'"/></a>');
		}
	</script>
</body>
</html>