<div class="area">
	<div class="help"> 
		<p>帮助</p>
	</div>
	
	<?=$this->showErrors()?>
	
	<div class="nr">
		<h2>编辑视频集</h2>

		<form action="" method="post">
			<table width="100%" cellspacing="1" class="form">
			<tbody>
			    <tr>
				    <td width="80">标    题</td>
				    <td><input type="text" name="title" value="<?=$this->param('title', $this->set['title']) ?>" size="45" class="input"/></td>
			    </tr>
			    <tr class="alt">
				    <td>分    类</td>
				    <td><?=$this->formSelect('cid', $this->param('cid', $this->set['cid']), '', $this->categories)?></td>
			    </tr>
			    <tr>
				    <td>简　　介</td>
    				<td><textarea id="intro" name="intro" cols="" rows="" class="abs"><?=$this->param('intro', $this->set['intro']) ?></textarea></td>
			    </tr>
			    <tr>
	    			<td>&nbsp;</td>
		    		<td><button type="submit" name="submit">修改视频集</button></td>
			    </tr>
			</tbody>
			</table>
		</form>
	</div>
</div>