<script>
	function list(channel)
	{
		document.forms[0].channel.value=channel;
		document.forms[0].action='/count/index/index';
		document.forms[0].submit();
	}
	function changedatetype(obj)
	{
		switch(obj.value)
		{
			case 'day':
				$('#select_day').show();
				$('#select_month').show();
				$('#select_quarter').hide();
				$('#select_week').hide();
				$('#join').hide();
				$('#select_end_year').hide();
				$('#select_end_month').hide();
				$('#select_end_day').hide();
				break;
			case 'month':
				$('#select_day').hide();
				$('#select_month').show();
				$('#select_quarter').hide();
				$('#select_week').hide();
				$('#join').hide();
				$('#select_end_year').hide();
				$('#select_end_month').hide();
				$('#select_end_day').hide();
				break;
			case 'week':
				$('#select_day').hide();
				$('#select_month').hide();
				$('#select_quarter').hide();
				$('#select_week').show();
				$('#join').hide();
				$('#select_end_year').hide();
				$('#select_end_month').hide();
				$('#select_end_day').hide();
				break;
			case 'quarter':
				$('#select_day').hide();
				$('#select_month').hide();
				$('#select_quarter').show();
				$('#select_week').hide();
				$('#join').hide();
				$('#select_end_year').hide();
				$('#select_end_month').hide();
				$('#select_end_day').hide();
				break;
			case 'year':
				$('#select_day').hide();
				$('#select_month').hide();
				$('#select_quarter').hide();
				$('#select_week').hide();
				$('#join').hide();
				$('#select_end_year').hide();
				$('#select_end_month').hide();
				$('#select_end_day').hide();
				break;
			case 'custom':
				$('#select_day').show();
				$('#select_month').show();
				$('#select_quarter').hide();
				$('#select_week').hide();
				$('#join').show();
				$('#select_end_year').show();
				$('#select_end_month').show();
				$('#select_end_day').show();
				break;
		}
	}
	$(document).ready(function(){
		changedatetype($('#datetype')[0]);
	});
</script>

<div class="area">
	<div class="help">
    <p>帮助</p>
    <p>1、此处为约稿统计列表;</p>    
    <p class="soart">
    	<form action="" name="search_form" method="post">
    		<input type="hidden" name="channel" value="">
            <span>日期类型:<?=$this->formSelect('datetype', $this->datetype, array('onchange'=>'changedatetype(this)'), $this->datetypes)?></span>
            <span><?=$this->formSelect('year', $this->year, null, $this->years)?>年</span>
            <span id="select_month"><?=$this->formSelect('month', $this->month, null, $this->months)?>月</span>
            <span id="select_day"><?=$this->formSelect('day', $this->day, null, $this->days)?>日</span>
            <span id="select_quarter"><?=$this->formSelect('quarter', $this->quarter, null, $this->quarters)?>季度</span>
            <span id="select_week"><?=$this->formSelect('week', $this->week, null, $this->weeks)?>周</span>
            <span id="join">至&nbsp;&nbsp;</span>
            <span id="select_end_year"><?=$this->formSelect('end_year', $this->end_year, null, $this->years)?>年</span>
            <span id="select_end_month"><?=$this->formSelect('end_month', $this->end_month, null, $this->months)?>月</span>
            <span id="select_end_day"><?=$this->formSelect('end_day', $this->end_day, null, $this->days)?>日</span>
            <input type="submit" value="显示"></button>
        </form>
    </p>    
    </div>
	<div class="nr">
    	<table cellpadding="0" cellspacing="0" border="0" width="100%" class="list">
        	<tr>
            	<th>作者</th>
                <th>文章数</th>
				<th>专题数</th>
                <th>浏览量</th>
                <!--th>评论量</th-->
                <th>稿件字数</th>
                <th>详细</th>
            </tr>
	<?php
		$count = 0;
		$fcount = 0;
		$totalhits = 0;
		$totalsize = 0;
	?>
    <?php if(!empty($this->data)){ foreach ($this->data as $key => $value): ?>
	<?php	
		if (is_numeric($value[article])) $count += $value['article'];
        if (is_numeric($value[focus])) $fcount += $value['focus'];
        if (is_numeric($value[pv])) $totalhits += $value['pv'];
        if (is_numeric($value[content_length])) $totalsize += $value['content_length'];	
	?>
            <tr>
        		<td><?=$value['channelname']?></td>
                <td><?=$value['article']?></td>
				<td><?=$value['focus']?></td>
                <td><?=$value['pv']?></td>
                <!--td><?=$value['comments']?></td-->
                <td><?=$value['content_length']?></td>
                <td><a href="#here" onclick="list('<?=$value['channel']?>')">详细</a></td>
            </tr>
    <?php endforeach;  }?>
	 <tr style="color:red">
		<td>合计</td>	
		<td><?=$count?></td>
		<td><?=$fcount?></td>
		<td><?=$totalhits?></td>	
		<td><?=$totalsize?></td>
		<td>--</td>
	  </tr>
        </table>
    </div>
    </div>

