<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<title>首页头条预览</title>
<meta name="description" content="首页头条预览" />
<meta name="keywords" content="首页头条预览" />
<link type="text/css" rel="stylesheet" href="/styles/nstyle0430.css" media="all" title="主样式" />
<style>
.headlines { height:450px; overflow:hidden; }
</style>
</head>

<body>
<div class="main">
  <div class="content">
    <div class="clearfix">      
      <div class="fl384">
<!--contentforhomepage-->
<div class="comcon headlines">
<?=stripslashes($this->contentHtml);?>
</div>
<!--contentforhomepage-->
</div>
</div>
</div>
</div>
</body>
</html>
