<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>CMS_管理</title>
<?=$this->headLink() ?>
<?=$this->headScript() ?>
</head>

<body>
<div class="area">
	<div class="help">
	    <p>帮助</p>
	    <p>1、此处为文章来源列表;</p>    
    </div>
	<div class="nr">
    	<h2>
        	<a href="/contents/publisher/add/">新建来源</a>
        </h2>
        <table cellpadding="0" cellspacing="0" border="0" width="100%" class="list">
        	<tr>
            	<th>ID</th>
                <th>来源名称</th>
                <th>来源图标</th>
                <th>来源URL</th>
                <th>操作</th>
            </tr>
    <?php foreach ($this->result as $k => $value): ?>
		    <tr>
		        <td><?=$value['id']?></td>
		        <td><a href="/contents/article/?publisher_id=<?=$value['id'] ?>"><?=$this->escape($value['name']) ?></a></td>
		        <td><?=$this->escape($value['img']) ?></td>
		        <td><?=$this->escape($value['url']) ?></td>
		        <td>
		            <a href="#here" onclick="window.location='/contents/publisher/edit/id/<?=$value['id'] ?>'">编辑</a> |
		            <a href="#here" onclick="if(confirm('确定删除吗?'))window.location='/contents/publisher/delete/id/<?=$value['id'] ?>'">删除</a>
		        </td>
		    </tr>
    <?php endforeach;  ?>

        </table>
        
     </div>
     
      <div class="fy">
		<div class="fpage"><?=$this->pagebar ?>
			<!--a href="#">&lt;&lt;</a>
			<a href="#">1</a>
			<a href="#" class="current">2</a>
			<a href="#">3</a>
			<a href="#">4</a>
			<a href="#">5</a>
			<a href="#">6</a>
			<a href="#">7</a>
			<a href="#">8</a>
			<a href="#">&gt;&gt;</a>
			<input name="" type="text" class="input" />
			<a href="#">GO</a>
			(2/1200)total-->
		</div>
	</div>  
</div>
</body>
</html>
