<script type="text/javascript" src="/scripts/jquery/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="/scripts/date/WdatePicker.js"></script>
<div class="area">
<div class="help"> 
	<p>帮助</p>
	<p>1、任务添加页面;</p>  
<?=$this->showErrors()?>
</div>

<div class="nr">
 	<h2>添加任务</h2>

<form action="" method="post">
<table width="100%" cellspacing="1" class="form">
<tbody>
    <tr>
        <td width="70">任务名称</td>
        <td><input type="text" name="taskName" value="<?=$this->escape($this->param('taskName'))?>" class="input"/></td>
    </tr>
    <tr class="alt">
        <td>任务简介</td>
        <td><textarea name="taskDesc" cols="50" rows="5"><?=$this->escape($this->param('taskDesc'))?></textarea></td>
    </tr>
    <tr>
        <td>任务类型</td>
        <td><?=$this->formSelect('taskType', $this->param('taskType'), null, $this->taskTypes)?></td>
    </tr>
    <tr class="alt">
        <td>跳转地址</td>
        <td><input type="text" name="jumpUrl" value="<?=$this->escape($this->param('jumpUrl'))?>" class="input"/></td>
    </tr>
    <tr class="alt">
        <td>任务积分</td>
        <td><input type="text" name="score" value="<?=$this->escape($this->param('score'))?>" class="input"/></td>
    </tr>
    <tr class="alt">
        <td>任务步数</td>
        <td><input type="text" name="step" value="<?=$this->escape($this->param('step'))?>" class="input"/></td>
    </tr>
    <tr class="alt">
        <td>开始时间</td>
        <td><input type="text" id="startTime" name="startTime" value="<?=$this->escape($this->param('startTime'))?>" class="input"/></td>
    </tr>
    <tr class="alt">
        <td>结束时间</td>
        <td><input type="text" id="endTime" name="endTime" value="<?=$this->escape($this->param('endTime'))?>" class="input"/></td>
    </tr>
    <tr>
        <td>是否显示</td>
        <td><?=$this->formSelect('isShow', $this->param('isShow'), null, array(0=>'不显示',1=>'显示'))?></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td><button type="submit" name="submit">添加任务</button></td>
    </tr>    
</tbody>
</table>
</form>
</div>
</div>
<script type="text/javascript">
        var $start_time = $('#startTime'),
            $end_time = $('#endTime');   
        // 日期选择
        $start_time.click(function(){
            WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'});
        });
        $end_time.click(function(){
            WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'});
        });
</script>