<script type="text/javascript" src="/scripts/jquery/jquery-1.3.2.min.js"></script>
<script type="text/javascript" src="/scripts/date/WdatePicker.js"></script>
<div class="area">
<div class="help"> 
	<p>帮助</p>
	<p>1、任务编辑页面;</p>  
<?=$this->showErrors()?>
</div>

<div class="nr">
 	<h2>编辑任务</h2>

<form action="" method="post">
<table cellspacing="1" class="form">
<tbody>
    <tr>
        <td width="70">任务id</td>
        <td><?=$this->task->id ?></td>
    </tr>
    <tr>
        <td>任务名称</td>
        <td><input style="width:100px;" name="taskName" value="<?=$this->param('taskName', $this->task->taskName) ?>"/></td>
    </tr>
    <tr class="alt">
        <td>任务描述</td>
        <td><input style="width:400px;" name="taskDesc" value="<?=$this->param('taskDesc', $this->task->taskDesc) ?>"/></td>
    </tr>
    <tr>
        <td>任务类型</td>
        <td><?=$this->formSelect('taskType', $this->param('taskType', $this->task->taskType), null, $this->taskTypes)?></td>
    </tr>  
    <tr>
        <td width="100">跳转地址</td>
        <td><input style="width:200px;" name="jumpUrl" value="<?=$this->task->jumpUrl ?>"></td>
    </tr>
    <tr>
        <td width="100">任务积分</td>
        <td><input style="width:100px;" name="score" value="<?=$this->task->score ?>"></td>
    </tr>
    <tr>
        <td width="100">任务步数</td>
        <td><input style="width:100px;" name="step" value="<?=$this->task->step ?>"></td>
    </tr>
    <tr>
        <td width="100">开始时间</td>
        <td><input style="width:200px;" id="startTime" name="startTime" value="<?=date('Y-m-d H:i:s',$this->task->startTime) ?>"></td>
    </tr>
    <tr>
        <td width="100">结束时间</td>
        <td><input style="width:200px;" id="endTime" name="endTime" value="<?=date('Y-m-d H:i:s',$this->task->endTime) ?>"></td>
    </tr>
    <tr>
        <td width="100">是否显示</td>
        <td><?=$this->formSelect('isShow', $this->param('isShow', $this->task->isShow), null, array(0=>'不显示',1=>'显示'))?></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td><button  type="submit" name="submit">编辑任务</button></td>
    </tr>  
</tbody>
</table>
</form>
</div>
</div>
<script type="text/javascript">
        var $start_time = $('#startTime'),
            $end_time = $('#endTime');   
        // 日期选择
        $start_time.click(function(){
            WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'});
        });
        $end_time.click(function(){
            WdatePicker({dateFmt:'yyyy-MM-dd HH:mm:ss'});
        });
</script>