<div class="area">
	<div class="help">
	    <p>帮助</p>
	    <p>1、此处为用户列表;</p>    
    <p class="soart">
    	<form action="/system/user/" name="search_form" method="post" onsubmit="on_submit(this)">
        	<label>用户名:<input class="input" type="text" name="username" value="<?=$this->username?>" size="16" /></label>
            <label>真实姓名:<input class="input" type="text" name="realname" value="<?=$this->realname?>" size="8" /></label>
            <input type="submit" value="显示"></button>
        </form>
    </p>    
    </div>
	<div class="nr">
    <h2><button onclick="window.location.href='/integral/task/create'">添加任务</button>用户组</h2>
        <table cellpadding="0" cellspacing="0" border="0" width="100%" class="list">
        	<tr>
            	<th width="1"></th>
            	<th>ID</th>
                <th>任务名称</th>
                <th>任务描述</th>
                <th>任务类型</th>
                <th>积分</th>
                <th>开始时间-结束时间</th>
                <th>是否显示</th>
                <th>操作</th>
                
            </tr>
    <?php foreach ($this->tasks as $k => $task): ?>
            <tr>
		        <td style="background-color: <?=$task['active'] ? '#9c0' : '#ccc' ?>"></td>
		        <td><?=$task['id']?></td>
		        <td><?=$this->escape($task['taskName']) ?></td>
		        <td><?=$this->escape($task['taskDesc']) ?></td>
		        <td><?=$this->taskTypes[$task['taskType']]?></td>
		        <td><?=$task['score']?></td>
                <td><?=date('Y-m-d H:i:s',$task['startTime'])?>---<?=date('Y-m-d H:i:s',$task['endTime'])?></td>
		        <td><?=$task['isShow']==0?'不显示':'显示'?></td>
                <td>
		            <a href="/integral/task/edit/id/<?=$task['id'] ?>">编辑</a>
		        </td>
            </tr>
    <?php endforeach;  ?>

        </table>
        
     </div>
     
	<div class="fy">
		<?=$this->pagebar ?>
	</div>  
</div>
