<div class="area">
<div class="help"> 
	<p>帮助</p>
	<p>1、投票主题添加页面，具体投票问题请在投票主题的问题管理下添加，一个投票主题可以包含多个投票;</p> 
	<p>2、此处为投票主题，非具体投票的标题。单问题投票此题目与投票标题相同;</p>
	<p>3、关闭状态不判断其他任何条件,不接受投票,活动状态根据时间来决定是否接受投票。</p> 
	
</div>
<div class="nr">
<h2>
<button onclick="window.location.href='/vote/index/'">返回</button>
<a href="#nogo">添加投票主题</a>        	
</h2>
	<form action="/vote/index/create" method="post">
	<table cellpadding="0" cellspacing="0" border="0" width="100%" class="list">
	<tbody>
		<tr>
			<td>投票主题</td>
			<td><input type="text" name="title"  size="40"/>此处为投票主题，非具体投票的标题。</td>
		</tr>
		<tr>
			<td>开始时间</td>			
			<td><input name="starttime" type="text" size="20"  onclick="new WdatePicker({startDate:'%y-%M-%d %h:%i:%s',dateFmt:'yyyy-MM-dd HH:mm:ss',alwaysUseStartDate:false});" value="" /></td>
		</tr>
		<tr>
			<td>结束时间</td>
			<td><input name="endtime" type="text" size="20"  onclick="new WdatePicker({startDate:'%y-%M-%d %h:%i:%s',dateFmt:'yyyy-MM-dd HH:mm:ss',alwaysUseStartDate:false});" value=""  /></td>
		</tr>
		<tr class="alt">
			<td>状态</td>
			<td><select name="status" >				
					<option value="1" label="正常">正常</option>
					<option value="2" label="过期">过期</option>
					<option value="3" label="关闭">关闭</option>
					<option value="4" label="停止">停止</option>
					<option value="5" label="删除">删除</option>				
				</select></td>
		</tr>	
		<tr>
			<td></td>
			<td align="left"><input type="submit" value="   提 交   " /></td>
		</tr>
	</tbody>
	</table>
	</form>
	</div>
</div>

