<div class="area">
<div class="help"> 
	<p>帮助</p>
	<p>1、用户添加页面;</p>  
<?=$this->showErrors()?>
</div>

<div class="nr">
 	<h2>添加用户</h2>

<form action="" method="post">
<table width="100%" cellspacing="1" class="form">
<tbody>
    <tr>
        <td width="70">用 户 名</td>
        <td><input type="text" name="username" value="<?=$this->param('username') ?>" class="input"/></td>
    </tr>
    <tr class="alt">
        <td>密　　码</td>
        <td><input type="password" name="password" value="<?=$this->param('password') ?>"  class="input"/></td>
    </tr>
    <tr>
        <td>确认密码</td>
        <td><input type="password" name="password_alt" value="<?=$this->param('password_alt') ?>" class="input"/></td>
    </tr>
    <tr>
        <td>姓　　名</td>
        <td><input type="text" name="realname" value="<?=$this->param('realname', $this->user->realname) ?>"  class="input"/></td>
    </tr>
    <tr class="alt">
        <td>email</td>
        <td><input type="text" name="email" value="<?=$this->param('email', $this->user->email) ?>"  class="input"/></td>
    </tr>
    <tr>
        <td>权限频道</td><td>
	<?php foreach($this->channels as $key => $value):?>
        <input type="checkbox" name="channels[]" value="<?=$key?>"><?=$value?>
    <?php endforeach;?>
    </td></tr>
    <tr>
        <td>&nbsp;</td>
        <td><button type="submit" name="submit">添加用户</button></td>
    </tr>    
</tbody>
</table>
</form>
</div>
</div>