<div class="area">
	<div class="help">
	    <p>帮助</p>
	    <p>1、此处为用户列表;</p>    
    <p class="soart">
    	<form action="/system/user/" name="search_form" method="post" onsubmit="on_submit(this)">
        	<label>用户名:<input class="input" type="text" name="username" value="<?=$this->username?>" size="16" /></label>
            <label>真实姓名:<input class="input" type="text" name="realname" value="<?=$this->realname?>" size="8" /></label>
            <input type="submit" value="显示"></button>
        </form>
    </p>    
    </div>
	<div class="nr">
        <table cellpadding="0" cellspacing="0" border="0" width="100%" class="list">
        	<tr>
            	<th width="1"></th>
            	<th>ID</th>
                <th>用户名</th>
                <th>姓名</th>
                <th>用户组</th>
                <th>加入日期</th>
                <th>操作</th>
                
            </tr>
    <?php foreach ($this->users as $k => $user): ?>
            <tr>
		        <td style="background-color: <?=$user['active'] ? '#9c0' : '#ccc' ?>"></td>
		        <td><?=$user['uid']?></td>
		        <td><?=$this->escape($user['username']) ?></td>
		        <td><?=$this->escape($user['realname']) ?></td>
		        <td><?=empty($user['groupname'])?'<font color="red">未定义</font>':$user['groupname'] ?></td>
		        <td><?=$user['joindate'] ?></td>
		        <td>
		            <a href="/system/user/edit/uid/<?=$user['uid'] ?>">编辑</a>
		        </td>
            </tr>
    <?php endforeach;  ?>

        </table>
        
     </div>
     
	<div class="fy">
		<?=$this->pagebar ?>
	</div>  
</div>
